### ISSUE TITLE
tuple index out of range

### ISSUE THREAD

**Issue by algoherif** [mick-liu/tagenalgo#3]
i got that error, please help

![image](https://user-images.githubusercontent.com/80507297/110902190-84796700-8316-11eb-8042-fbf3dfd2264c.png)

**Comment by mick-liu** [comment]
> i got that error, please help

Hi, Since I don't have enough information, could you pls paste complete codes you used in the following form? I will do my best to help you out.
```
# Example
# pls paste your codes.
```

**Comment by Steven-Herrera** [comment]
I think the problem is that _fitness_cal(self, params, sig_total=0.03) only returns fitness_val_cumret, fitness_val_winrate but _fitness_evaluation(self, pop) is attempting to obtain self._fitness_cal(ind)[2] when it doesn't exist.

**Comment by sierret** [comment]
> I think the problem is that _fitness_cal(self, params, sig_total=0.03) only returns fitness_val_cumret, fitness_val_winrate but _fitness_evaluation(self, pop) is attempting to obtain self._fitness_cal(ind)[2] when it doesn't exist.

And how would this best be fixed?

(I am having the same issue)
Traceback (most recent call last):
  File "/home/-/OptRSI.py", line 26, in <module>
    model.fit(init_pop)
  File "/home/-/tagenalgo/tagenalgo.py", line 311, in fit
    pop_fit = self._fitness_evaluation(pop)
  File "/home/-/tagenalgo/tagenalgo.py", line 249, in _fitness_evaluation
    win_pat.append(self._fitness_cal(ind)[2])
IndexError: tuple index out of range
